version: "3.9"

name: tribler
services:
  tribler:
    image: rshmyrev/tribler
    build: .
    hostname: debian
    environment:
      - DISPLAY=unix$DISPLAY # X11
      - PULSE_SERVER=unix:$XDG_RUNTIME_DIR/pulse/native # PulseAudio
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro # X11
      - $XDG_RUNTIME_DIR/pulse:$XDG_RUNTIME_DIR/pulse:ro # PulseAudio
      - data:/data # Tribler data (/home/user/.Tribler)
      - $HOME/Downloads:/downloads # Tribler Downloads

volumes:
  data:
